version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL_SERVER_SA_PASSWORD}
      - MSSQL_PID=Express
      - DATABASE_PUBLIC_URL=db
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql
      - ./database.sql:/var/opt/mssql/database.sql

  backendRinku:
    image: backend_rinku
    build:
      context: backendRinku
      dockerfile: Dockerfile
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_DIALECT=${DATABASE_DIALECT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_PORT=${DATABASE_PORT}
      - API_PORT=${API_PORT}
    ports:
      - "3000:3000"
    depends_on:
      - sqlserver

  frontendRinku:
    image: frontend_rinku
    build:
      context: frontendRinku
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backendRinku
